#DB 설정
#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: awseb-e-jntpwwy2nv-stack-awsebrdsdatabase-xkusmh3dto0s.ceex1ugfcfad.ap-northeast-2.rds.amazonaws.com:3306
#    username: jin
#    password: 12345678

#JPA 설정
#  jpa:
#    database-platform:
#    hibernate:
#      ddl-auto: create

#배포 할 떄는 open-in-view false 설정
#    open-in-view: false
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
